"""Mechanical vehicle identity selection/proof for the ALLDATA Navigator.

This module deliberately owns *identity only*.  It never decides which ADAS
system, article, procedure, or calibration is relevant.  X owns those semantic
choices.  ScrapeX only makes sure the browser is actually bound to the vehicle
X asked for before semantic navigation starts and when evidence is verified.

Why this exists:
- The live Navigator originally treated any accessible year/make/model text as
  proof of the selected vehicle.  A matching picker result or Recent Vehicles
  link could therefore make the wrong browser vehicle look verified.
- VIN selection already has a mechanical provider fast path.  ROs without a
  VIN need the same kind of bounded, fail-closed identity step for Y/M/M.

The provider keeps the most recent mechanically-proven identity in memory.
X's primary-task anchor re-runs this selection for every new vehicle, so a
procedure page left open by the previous task cannot satisfy the next task's
identity check.  Ambiguous Y/M/M configurations are reported rather than
silently guessed.
"""

from __future__ import annotations

import json
import re
from typing import Any
from urllib.parse import urljoin

from . import alldata as alldata_heuristics
from .alldata_navigator import (
    AlldataNavigatorProvider,
    PICKER_URL,
    _SEARCH_BOX_SELECTORS,
)
from .models import VehicleSpec
from .navigator_observation import build_observation

_INSTALLED_ATTR = "__scrapex_task_safe_vehicle_identity_v1__"
_VIN_RE = re.compile(r"^[A-HJ-NPR-Z0-9]{17}$")
_VEHICLE_ROUTE_RE = re.compile(r"/vehicle/([^/?#]+)", re.I)
_INTERACTIVE_ROLES = frozenset(
    {
        "link",
        "button",
        "option",
        "row",
        "menuitem",
        "tab",
        "treeitem",
        "combobox",
        "textbox",
        "searchbox",
    }
)


def _norm(value: Any) -> str:
    return " ".join(str(value or "").casefold().split())


def _valid_year(value: Any) -> int | None:
    try:
        year = int(value)
    except (TypeError, ValueError):
        return None
    return year if 1900 <= year <= 2100 else None


def _ymm_from_action(action: dict[str, Any]) -> dict[str, Any] | None:
    """Decode the internal Y/M/M selection payload carried in ``text``.

    ``text`` is already part of ScrapeX's bounded Navigator action contract, so
    this keeps the public HTTP model stable while X's internal primary-task
    anchor can request mechanical Y/M/M selection.  The model-facing
    ``select_vehicle`` tool remains VIN-oriented; this payload is generated by
    runtime code from an already-resolved CIQ target, never from model prose.
    """
    raw = action.get("text")
    if not isinstance(raw, str) or not raw.strip():
        return None
    try:
        parsed = json.loads(raw)
    except (TypeError, ValueError, json.JSONDecodeError):
        return None
    if not isinstance(parsed, dict):
        return None
    year = _valid_year(parsed.get("year"))
    make = str(parsed.get("make") or "").strip()
    model = str(parsed.get("model") or "").strip()
    if year is None or not make or not model:
        return None
    if max(len(make), len(model), len(str(parsed.get("trim") or ""))) > 120:
        return None
    return {
        "year": year,
        "make": make,
        "model": model,
        "trim": str(parsed.get("trim") or "").strip() or None,
        "engine": str(parsed.get("engine") or "").strip() or None,
    }


def _identity_key(target: dict[str, Any]) -> tuple[Any, ...] | None:
    vin = "".join(str(target.get("vin") or "").split()).upper()
    if _VIN_RE.fullmatch(vin):
        return ("vin", vin)
    year = _valid_year(target.get("year"))
    make = _norm(target.get("make"))
    model = _norm(target.get("model"))
    if year is None or not make or not model:
        return None
    return ("ymm", year, make, model, _norm(target.get("trim")))


def _proof_matches(proof: Any, target: dict[str, Any]) -> bool:
    return isinstance(proof, dict) and proof.get("key") == _identity_key(target)


async def _static_ymm_signal(page: Any, vehicle: VehicleSpec) -> str | None:
    """Return a non-interactive rendered Y/M/M identity signal, if one exists.

    Search results, Recent Vehicles links, options, buttons and rows are
    intentionally excluded.  Those elements prove only that a vehicle *could*
    be selected, not that it *is* selected.
    """
    try:
        observation = await build_observation(page)
    except Exception:
        return None
    for element in observation.elements:
        role = str(getattr(element, "role", "") or "").casefold()
        name = str(getattr(element, "name", "") or "")
        if role in _INTERACTIVE_ROLES:
            continue
        if name and alldata_heuristics.vehicle_matches(name, vehicle):
            return name
    return None


async def _strict_page_signal(page: Any, target: dict[str, Any]) -> dict[str, Any]:
    """Fail-closed live-page proof used when no mechanical receipt is present."""
    url = str(getattr(page, "url", "") or "")
    if "/select-vehicle" in url.casefold():
        return {
            "selected": False,
            "reason": "The ALLDATA vehicle picker is open; a search result is not selected-vehicle proof.",
            "proof": "picker_not_identity",
        }

    vin = "".join(str(target.get("vin") or "").split()).upper()
    if _VIN_RE.fullmatch(vin):
        try:
            body = await page.locator("body").inner_text(timeout=2_500)
        except Exception:
            body = ""
        if vin in "".join(str(body or "").split()).upper():
            return {"selected": True, "reason": None, "label": vin, "proof": "rendered_vin"}
        return {
            "selected": False,
            "reason": "The rendered ALLDATA page does not show the requested VIN.",
            "proof": "vin_not_rendered",
        }

    year = _valid_year(target.get("year"))
    make = str(target.get("make") or "").strip()
    model = str(target.get("model") or "").strip()
    if year is None or not make or not model:
        return {"selected": False, "reason": "The vehicle target is incomplete."}

    # A picker/list page can contain many matching vehicle choices.  Require a
    # selected vehicle route before considering rendered Y/M/M text as proof.
    if _VEHICLE_ROUTE_RE.search(url) is None:
        return {
            "selected": False,
            "reason": "ALLDATA is not on a selected vehicle route.",
            "proof": "no_vehicle_route",
        }
    vehicle = VehicleSpec(
        year=year,
        make=make,
        model=model,
        trim=target.get("trim"),
        vin=None,
    )
    label = await _static_ymm_signal(page, vehicle)
    if label:
        return {
            "selected": True,
            "reason": None,
            "label": label,
            "proof": "rendered_noninteractive_ymm",
        }
    return {
        "selected": False,
        "reason": "ALLDATA did not expose a non-interactive selected-vehicle Y/M/M signal.",
        "proof": "ymm_not_proven",
    }


async def _search_box(page: Any):
    for selector in _SEARCH_BOX_SELECTORS:
        candidate = page.locator(selector).first
        try:
            if await candidate.is_visible(timeout=1_500):
                return candidate
        except Exception:
            continue
    return None


async def _candidate_rows(page: Any, vehicle: VehicleSpec) -> list[tuple[int, str, Any, str | None]]:
    locs = page.locator("a,button,[role='option'],[role='row'],[role='link'],li")
    found: list[tuple[int, str, Any, str | None]] = []
    try:
        count = min(await locs.count(), 350)
    except Exception:
        return found
    for index in range(count):
        loc = locs.nth(index)
        text = await alldata_heuristics._text(loc)
        if not text or len(text) > 500 or not alldata_heuristics.vehicle_matches(text, vehicle):
            continue
        score = 10
        if vehicle.trim and alldata_heuristics.plain(vehicle.trim) in alldata_heuristics.plain(text):
            score += 4
        if vehicle.engine and alldata_heuristics.plain(vehicle.engine) in alldata_heuristics.plain(text):
            score += 3
        href: str | None = None
        try:
            href = await loc.get_attribute("href")
        except Exception:
            href = None
        found.append((score, text, loc, href))
    found.sort(key=lambda item: (item[0], -len(item[1])), reverse=True)
    return found


async def _select_ymm(self: AlldataNavigatorProvider, page: Any, target: dict[str, Any]) -> dict[str, Any]:
    vehicle = VehicleSpec(
        year=target["year"],
        make=target["make"],
        model=target["model"],
        trim=target.get("trim"),
        engine=target.get("engine"),
        vin=None,
    )
    try:
        await page.goto(PICKER_URL, wait_until="load")
        await page.wait_for_timeout(1_500)
    except Exception as exc:  # noqa: BLE001
        return {"selected": False, "reason": f"The vehicle picker did not open: {type(exc).__name__}."}

    box = await _search_box(page)
    if box is None:
        return {"selected": False, "reason": "The vehicle search box was not on the picker."}
    query = f"{vehicle.year} {vehicle.make} {vehicle.model}"
    try:
        await box.click(timeout=5_000)
        # The live ALLDATA picker reacts to real keystrokes; programmatic fill
        # can leave the result list unchanged.
        try:
            await page.keyboard.press("Control+A")
        except Exception:
            pass
        await page.keyboard.type(query, delay=25)
        await page.wait_for_timeout(1_200)
    except Exception as exc:  # noqa: BLE001
        return {"selected": False, "reason": f"Typing the Y/M/M search failed: {type(exc).__name__}."}

    found = await _candidate_rows(page, vehicle)
    if not found:
        return {
            "selected": False,
            "reason": "No exact year/make/model candidate was visible in ALLDATA.",
            "query": query,
        }
    best_score = found[0][0]
    tied = [item for item in found if item[0] == best_score]
    distinct = list(dict.fromkeys(alldata_heuristics.plain(item[1]) for item in tied))
    if len(distinct) > 1 and not (vehicle.trim or vehicle.engine):
        return {
            "selected": False,
            "needs_operator": True,
            "reason": "Multiple equally plausible ALLDATA vehicle configurations match this year/make/model.",
            "query": query,
            "candidates": [item[1] for item in tied[:10]],
        }

    _, clicked_text, locator, href = found[0]
    expected_vehicle_id: str | None = None
    if href:
        absolute = urljoin(str(getattr(page, "url", PICKER_URL) or PICKER_URL), href)
        match = _VEHICLE_ROUTE_RE.search(absolute)
        expected_vehicle_id = match.group(1) if match else None
    try:
        await locator.click(timeout=6_000)
        await page.wait_for_timeout(1_000)
    except Exception as exc:  # noqa: BLE001
        return {"selected": False, "reason": f"Vehicle candidate click failed: {type(exc).__name__}."}

    final_url = str(getattr(page, "url", "") or "")
    route_match = _VEHICLE_ROUTE_RE.search(final_url)
    if route_match is None:
        return {
            "selected": False,
            "reason": "ALLDATA did not enter a selected vehicle route after the Y/M/M candidate click.",
            "clicked": clicked_text,
            "url": final_url,
        }
    if expected_vehicle_id and route_match.group(1) != expected_vehicle_id:
        return {
            "selected": False,
            "reason": "ALLDATA opened a different vehicle route than the Y/M/M candidate that was clicked.",
            "clicked": clicked_text,
            "url": final_url,
        }

    # The click itself is bounded to an exact Y/M/M candidate.  Prefer a
    # rendered selected-vehicle signal too when ALLDATA exposes one, but the
    # candidate destination route is already a mechanical binding when href
    # supplied the exact vehicle id.
    live = await _strict_page_signal(
        page,
        {"year": vehicle.year, "make": vehicle.make, "model": vehicle.model, "trim": vehicle.trim},
    )
    if expected_vehicle_id is None and live.get("selected") is not True:
        return {
            "selected": False,
            "reason": str(live.get("reason") or "Could not prove the Y/M/M selection after the click."),
            "clicked": clicked_text,
            "url": final_url,
        }

    proof_target = {
        "year": int(vehicle.year),
        "make": vehicle.make,
        "model": vehicle.model,
        "trim": vehicle.trim,
    }
    proof = {
        "key": _identity_key(proof_target),
        "mode": "year_make_model",
        "label": clicked_text,
        "vehicle_id": expected_vehicle_id or route_match.group(1),
    }
    setattr(self, "_x_selected_identity", proof)
    return {
        "selected": True,
        "verified": True,
        "identity_mode": "year_make_model",
        "year": int(vehicle.year),
        "make": vehicle.make,
        "model": vehicle.model,
        "trim": vehicle.trim,
        "label": clicked_text,
        "vehicle_id": proof["vehicle_id"],
        "url": final_url,
        "proof": "clicked_matching_candidate_and_vehicle_route",
    }


def install() -> None:
    if getattr(AlldataNavigatorProvider, _INSTALLED_ATTR, False):
        return

    original_select_vehicle = AlldataNavigatorProvider.select_vehicle

    async def select_vehicle(self: AlldataNavigatorProvider, page: Any, action: dict[str, Any]) -> dict[str, Any]:
        vin = "".join(str(action.get("vin") or "").split()).upper()
        if _VIN_RE.fullmatch(vin):
            result = await original_select_vehicle(self, page, action)
            if isinstance(result, dict) and result.get("selected") is True:
                setattr(
                    self,
                    "_x_selected_identity",
                    {"key": ("vin", vin), "mode": "vin", "label": result.get("label")},
                )
            return result

        ymm = _ymm_from_action(action)
        if ymm is None:
            return {
                "selected": False,
                "reason": "select_vehicle requires either an exact 17-character VIN or a valid internal Y/M/M identity payload.",
            }
        return await _select_ymm(self, page, ymm)

    async def target_signal(self: AlldataNavigatorProvider, page: Any, target: dict[str, Any]) -> dict[str, Any]:
        proof = getattr(self, "_x_selected_identity", None)
        if _proof_matches(proof, target):
            return {
                "selected": True,
                "reason": None,
                "label": proof.get("label"),
                "proof": "mechanical_selection_receipt",
                "identity_mode": proof.get("mode"),
            }
        # Never let arbitrary accessibility text (picker results / Recent
        # Vehicles links) establish identity.  If no current mechanical receipt
        # exists, use only the strict rendered proof above.
        return await _strict_page_signal(page, target)

    AlldataNavigatorProvider.select_vehicle = select_vehicle
    AlldataNavigatorProvider.target_signal = target_signal
    setattr(AlldataNavigatorProvider, _INSTALLED_ATTR, True)


install()
